webtalk_init -webtalk_dir F:\\SoC_Application\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-13 14:43:44" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174131902_174131903_210671458_965" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vrc83rebsa30aqtn3ahvh12p7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.513 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1542115712000" -context "sdk\\\\bsp/1542115712000"
webtalk_add_data -client sdk -key hwid -value "1541590348000" -context "sdk\\\\bsp/1542115712000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1542115712000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1542115712000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1542115712000"
webtalk_add_data -client sdk -key uid -value "1542115756000" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key hwid -value "1541590348000" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key bspid -value "1542115712000" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1542115756000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1542116623299"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1542116623299"
webtalk_transmit -clientid 1114673768 -regid "174131902_174131903_210671458_965" -xml F:\\SoC_Application\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\SoC_Application\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\SoC_Application\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
